#my variables
name: Aadesh Shrestha
description: just another blog
google_analytics: UA-77211589-1
ulr: http://aadeshshrestha.me
# baseurl: "/example"

include: [".htaccess"]
gems: [jekyll-sitemap]

#css settings
sass:
  style: :compressed
  sass_dir: _sass
#Build settings
markdown: kramdown
