#my variables
name: Aadesh Shrestha
description: just another blog
google_analytics: UA-77211589-1
# baseurl: "/example"

include: [".htaccess"]

#css settings
sass:
  styple: :compressed
  sass_dir: _sass
#Build settings
markdown: kramdown
